### ISSUE TITLE
requests?

### ISSUE THREAD

**Issue by yani1shu** [gsj889/bitbucket-repo-size#1]
Trying to run and get error message:
  File "main.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by gnome506** [comment]
Added the requirements file in 80b59cd73551a62555fca85fb6e2e0c55a3b4d88. 

Run `pip install -r requirements.txt` or `pip install requests`

Also, you might want to check this out: https://stackoverflow.com/questions/30362600/how-to-install-requests-module-in-python-3-4-instead-of-2-7
